### ISSUE TITLE
Hero (Complex)

### ISSUE THREAD

**Issue by mtrythall** [rapidpro/chpro-microsite#12]
The Hero (Complex) component features the a title, background effect (TBD), rich text area, and an image.

It may accept Icon Cards.

![screenshot 2018-02-28 17 11 54](https://user-images.githubusercontent.com/84750/36815976-805108c0-1caa-11e8-8e5b-1ea394a6c5c2.png)

**Comment by nicolaslara** [comment]
I want to note that we need to choose if we want to support highly rich text editing (allowing, for example, internal links and images in the text) or subplugins (cards).  

This means that the complex hero will allow for cards, but not internal links in the text and images in the text. If we wanted to have both, we could split these so that we have a hero without child plugins and a standalone card list bellow.

**Comment by mtrythall** [comment]
I did some thinking and I think the 3 cards under the complex hero should be a card grid with an alternative style. It doesn't make sense to connect these.

What we can do, instead, is have the current homepage design used for cards. That should solve all our issues here and we can probably close out hero.

WYSIWYG issues can be separated out.

**Comment by nicolaslara** [comment]
That sounds good to me. This all depends on the design, if the cards need to know something about the hero above, we should connect them. Based on your comment above, it seems they don't.

Let's split the wysiwyg issues and allow card grids to use different styles

**Comment by mtrythall** [comment]
To clarify, because I realize I may have misspoke, we still need complex hero with Cards, it'll just look like the homepage. You can add multiple cards (not sure why you would). I don't see how else to do that, since I need to overlay the cards over the hero, and using 2 components to do that is confusing.

I'll build this out today.

**Comment by mtrythall** [comment]
The plugin issue sort of blocks this.
